name: Build LibPQCrypto

on:
  workflow_dispatch:
  
env:
  version: $(curl -s https://libpqcrypto.org/libpqcrypto-latest-version.txt)

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Install required packages
        run: sudo apt-get update && sudo apt-get install -y build-essential libssl-dev libgmp-dev python3

      - name: Download / unpack and build libpqcrypto
        run: |
          cd $HOME
          curl -LO https://libpqcrypto.org/libpqcrypto-$version.tar.gz
          tar -xf libpqcrypto-$version.tar.gz
          ln -s libpqcrypto-$version link-build
          ln -s libpqcrypto-$version link-install
          cd libpqcrypto-$version
          ./do

      - name: Create zip archive of compiled code
        if: success()
        run: |
          cd $HOME
          zip -r libpqcrypto-$version.zip libpqcrypto-$version
          mv libpqcrypto-$version.zip ${{ github.workspace }}

      - name: Upload compiled code as artifact
        if: success()
        uses: actions/upload-artifact@v3.1.2
        with:
          name: libpqcrypto-artifact
          path: ${{ github.workspace }}/libpqcrypto-$version.zip
