name: Build LibPQCrypto

on:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Install required packages
        run: sudo apt-get update && sudo apt-get install -y build-essential libssl-dev libgmp-dev python3

      - name: Download and unpack libpqcrypto
        run: |
          version=$(curl -s https://libpqcrypto.org/libpqcrypto-latest-version.txt)
          curl -LO https://libpqcrypto.org/libpqcrypto-$version.tar.gz
          tar xf libpqcrypto-$version.tar.gz -C $HOME
          ln -s $HOME/libpqcrypto-$version $HOME/link-build
          ln -s $HOME/libpqcrypto-$version $HOME/link-install

      - name: Compile, test, and install libpqcrypto
        run: |
          ./do

      - name: Create tarball of compiled code
        if: success()
        run: |
          tar -czf libpqcrypto-$version.tar.gz ~/libpqcrypto-$version
          mv libpqcrypto-$version.tar.gz ${{ github.workspace }}

      - name: Upload compiled code as artifact
        if: success()
        uses: actions/upload-artifact@v3.1.2
        with:
          name: libpqcrypto-artifact
          path: ${{ github.workspace }}/libpqcrypto-$version.tar.gz
